name: TVBox Processor

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git init
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch --all
          git checkout main

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd
          sudo apt-get install -y docker.io containerd.io python3-pip
          sudo systemctl start docker
          python3 -m pip install --upgrade pip

      - name: Run TVBox processor
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TVBOX_URLS: ${{ secrets.TVBOX_URLS }}
        run: python3 tvbox_processor.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update TVBox configs [skip ci]"
          git push
